import sqlite3

conn = sqlite3.connect('reviews.db')

conn.execute('''
	CREATE TABLE PRODUCT
	(ID INT PRIMARY KEY NOT NULL,
	PRODUCT_ID TEXT NOT NULL,
	PRODUCT_NAME TEXT NOT NULL,
	BRAND TEXT NOT NULL,
	SALE_PRICE REAL NOT NULL,
	LIST_PRICE REAL NOT NULL,
	DESCRIP TEXT NOT NULL,
	RANK INT NOT NULL,
	TITLE INT NOT NULL);''')

conn.close()